version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  http-go:
    lang: golang-http
    build_args:
      TARGETPLATFORM: linux/arm
    handler: ./http-go
    image: http-go:latest
    environment:
      TARGETPLATFORM: linux/arm

